### ISSUE TITLE
Android 9 infinity loading when pick image with cropping

### ISSUE THREAD

**Issue by vovaklh** [howljs/hl_image_picker#30]

**Comment by no-chili** [comment]
I encountered the same issue.

**Comment by JCKodel** [comment]
Logs:

```logs
I/BitmapCropTask( 8580): Should crop: true
W/Glide   ( 8580): Load failed for [/storage/emulated/0/Pictures/1720051631215.jpg] with dimensions [200x200]
W/Glide   ( 8580): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
W/Glide   ( 8580): There were 3 root causes:
W/Glide   ( 8580): java.io.FileNotFoundException(/storage/emulated/0/Pictures/1720051631215.jpg (No such file or directory))
2
W/Glide   ( 8580): java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
W/Glide   ( 8580):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 8580):   Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
W/Glide   ( 8580): There was 1 root cause:
W/Glide   ( 8580): java.io.FileNotFoundException(/storage/emulated/0/Pictures/1720051631215.jpg (No such file or directory))
W/Glide   ( 8580):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 8580):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
W/Glide   ( 8580): There was 1 root cause:
W/Glide   ( 8580): java.io.FileNotFoundException(/storage/emulated/0/Pictures/1720051631215.jpg (No such file or directory))
W/Glide   ( 8580):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 8580):       Cause (1 of 1): class java.io.FileNotFoundException: /storage/emulated/0/Pictures/1720051631215.jpg (No such file or directory)
W/Glide   ( 8580):   Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
W/Glide   ( 8580): There was 1 root cause:
W/Glide   ( 8580): java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
W/Glide   ( 8580):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 8580):     Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
W/Glide   ( 8580):   Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
W/Glide   ( 8580): There was 1 root cause:
W/Glide   ( 8580): java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
W/Glide   ( 8580):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 8580):     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
W/Glide   ( 8580): There was 1 root cause:
W/Glide   ( 8580): java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
W/Glide   ( 8580):  call GlideException#logRootCauses(String) for more detail
W/Glide   ( 8580):       Cause (1 of 1): class java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
I/Glide   ( 8580): Root cause (1 of 3)
I/Glide   ( 8580): java.io.FileNotFoundException: /storage/emulated/0/Pictures/1720051631215.jpg (No such file or directory)
I/Glide   ( 8580): 	at java.io.FileInputStream.open0(Native Method)
I/Glide   ( 8580): 	at java.io.FileInputStream.open(FileInputStream.java:231)
I/Glide   ( 8580): 	at java.io.FileInputStream.<init>(FileInputStream.java:165)
I/Glide   ( 8580): 	at java.io.FileInputStream.<init>(FileInputStream.java:112)
I/Glide   ( 8580): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1013)
I/Glide   ( 8580): 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResourceFromUri(StreamLocalUriFetcher.java:74)
I/Glide   ( 8580): 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:50)
I/Glide   ( 8580): 	at com.bumptech.glide.load.data.StreamLocalUriFetcher.loadResource(StreamLocalUriFetcher.java:13)
I/Glide   ( 8580): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
I/Glide   ( 8580): 	at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:100)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:280)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
I/Glide   ( 8580): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/Glide   ( 8580): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:424)
I/Glide   ( 8580): 	at java.lang.Thread.run(Thread.java:764)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:383)
I/Glide   ( 8580): Root cause (2 of 3)
I/Glide   ( 8580): 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313)
I/Glide   ( 8580): 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211)
I/Glide   ( 8580): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1290)
I/Glide   ( 8580): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1218)
I/Glide   ( 8580): 	at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:20)
I/Glide   ( 8580): 	at com.bumptech.glide.load.data.FileDescriptorLocalUriFetcher.loadResource(FileDescriptorLocalUriFetcher.java:12)
I/Glide   ( 8580): 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:95)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:88)
I/Glide   ( 8580): 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:311)
```
